export class SpaResponse {
    jd; //Julian day
    jc; //Julian century
    jde; //Julian ephemeris day
    jce; //Julian ephemeris century
    jme; //Julian ephemeris millennium
    l; //earth heliocentric longitude [degrees]
    b; //earth heliocentric latitude [degrees]
    r; //earth radius vector [Astronomical Units, AU]
    theta; //geocentric longitude [degrees]
    beta; //geocentric latitude [degrees]
    x0; //mean elongation (moon-sun) [degrees]
    x1; //mean anomaly (sun) [degrees]
    x2; //mean anomaly (moon) [degrees]
    x3; //argument latitude (moon) [degrees]
    x4; //ascending longitude (moon) [degrees]
    del_psi; //nutation longitude [degrees]
    del_epsilon; //nutation obliquity [degrees]
    epsilon0; //ecliptic mean obliquity [arc seconds]
    epsilon; //ecliptic true obliquity  [degrees]
    del_tau; //aberration correction [degrees]
    lamda; //apparent sun longitude [degrees]
    nu0; //Greenwich mean sidereal time [degrees]
    nu; //Greenwich sidereal time [degrees]
    alpha; //geocentric sun right ascension [degrees]
    delta; //geocentric sun declination [degrees]
    h; //observer hour angle [degrees]
    xi; //sun equatorial horizontal parallax [degrees]
    del_alpha; //sun right ascension parallax [degrees]
    delta_prime; //topocentric sun declination [degrees]
    alpha_prime; //topocentric sun right ascension [degrees]
    h_prime; //topocentric local hour angle [degrees]
    e0; //topocentric elevation angle (uncorrected) [degrees]
    del_e; //atmospheric refraction correction [degrees]
    e; //topocentric elevation angle (corrected) [degrees]
    eot; //equation of time [minutes]
    srha; //sunrise hour angle [degrees]
    ssha; //sunset hour angle [degrees]
    sta; //sun transit altitude [degrees]
    zenith; //topocentric zenith angle [degrees]
    azimuth_astro; //topocentric azimuth angle (westward from south) [for astronomers]
    azimuth; //topocentric azimuth angle (eastward from north) [for navigators and solar radiation]
    incidence; //surface incidence angle [degrees]
    suntransit; //local sun transit time (or solar noon) [fractional hour]
    sunrise; //local sunrise time (+/- 30 seconds) [fractional hour]
    sunset; //local sunset time (+/- 30 seconds) [fractional hour]
}